name: kyros
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.5
  flutter_quill: ^9.2.3
  path_provider: ^2.1.1
  path: ^1.8.3
  google_fonts: ^6.1.0
  firebase_app_check: ^0.2.1+8
  cloud_firestore: ^4.14.0
  http: ^1.1.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_carousel_widget: ^2.1.0
  sign_in_with_apple: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  timeago: ^3.6.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  flutter_quill_extensions: ^9.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/carousel_1.png
    - assets/images/carousel_2.png
    - assets/images/carousel_3.png
