name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  esv_bible: ^1.1.4
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  http: ^1.5.0
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  firebase_ai: ^3.3.0
  url_launcher: ^6.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
