name: kyros
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  flutter_quill: ^11.4.2
  intl: ^0.20.2
  path_provider: ^2.1.3
  path: ^1.9.0
  google_fonts: ^6.3.2
  firebase_app_check: ^0.4.1
  cloud_firestore: ^6.0.2
  http: ^1.2.1
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  carousel_slider: ^5.1.1
  sign_in_with_apple: ^7.0.1
  flutter_staggered_animations: ^1.1.1
  timeago: ^3.6.1
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  flutter_quill_extensions: ^11.0.0
  flutter_inappwebview: ^6.0.0
  flutter_gen: ^5.12.0
  flutter_svg: ^2.2.1
  firebase_storage: ^13.0.2
  glassmorphism: ^3.0.0
  record: ^6.1.1
  just_audio: ^0.10.5
  dynamic_color: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.19.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
