name: kyros
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.0.0
  flutter_quill: ^11.4.2
  path_provider: ^2.1.3
  path: ^1.9.0
  google_fonts: ^6.2.1
  firebase_app_check: ^0.4.1
  cloud_firestore: ^6.0.2
  http: ^1.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_carousel_widget: ^3.0.0
  sign_in_with_apple: ^7.0.0
  flutter_staggered_animations: ^1.1.1
  timeago: ^3.7.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  firebase_ai: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/carousel_1.png
    - assets/images/carousel_2.png
    - assets/images/carousel_3.png
