// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNTywucEoby6h17L614riTHK2hQdWURn8',
    appId: '1:896490665397:web:1259e373c20a92012d55fc',
    messagingSenderId: '896490665397',
    projectId: 'kyrosapp-100f7',
    authDomain: 'kyrosapp-100f7.firebaseapp.com',
    storageBucket: 'kyrosapp-100f7.firebasestorage.app',
    measurementId: 'G-XWQGCD4ZDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3x7-FkkrF3zr1Eosjy0DMI0nrtakguwU',
    appId: '1:896490665397:android:3b879838f5e3ae1c2d55fc',
    messagingSenderId: '896490665397',
    projectId: 'kyrosapp-100f7',
    storageBucket: 'kyrosapp-100f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEie2gkB_Hw3AY4j9dt28HzmMPrwh6ZE',
    appId: '1:896490665397:ios:4189532b31d76f912d55fc',
    messagingSenderId: '896490665397',
    projectId: 'kyrosapp-100f7',
    storageBucket: 'kyrosapp-100f7.firebasestorage.app',
    androidClientId:
        '896490665397-5b1annbcltanrdmbvoa87o89sa8fsb9l.apps.googleusercontent.com',
    iosClientId:
        '896490665397-kdas4htf5duu3rqr3d4ol5osqv7fog4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoEie2gkB_Hw3AY4j9dt28HzmMPrwh6ZE',
    appId: '1:896490665397:ios:4189532b31d76f912d55fc',
    messagingSenderId: '896490665397',
    projectId: 'kyrosapp-100f7',
    storageBucket: 'kyrosapp-100f7.firebasestorage.app',
    androidClientId:
        '896490665397-5b1annbcltanrdmbvoa87o89sa8fsb9l.apps.googleusercontent.com',
    iosClientId:
        '896490665397-kdas4htf5duu3rqr3d4ol5osqv7fog4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNTywucEoby6h17L614riTHK2hQdWURn8',
    appId: '1:896490665397:web:83031030ddba77652d55fc',
    messagingSenderId: '896490665397',
    projectId: 'kyrosapp-100f7',
    authDomain: 'kyrosapp-100f7.firebaseapp.com',
    storageBucket: 'kyrosapp-100f7.firebasestorage.app',
    measurementId: 'G-XPXXVMDJBD',
  );
}
