
name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0' # Using a recent stable version of Flutter

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test
